name: CI
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la

      - name: Install dependencies
        working-directory: lab-2-improve-code
        run: |
          yarn install

      - name: Build
        working-directory: lab-2-improve-code
        run: |
          yarn test build
        
      # - name: Codecov
      #   uses: codecov/codecov-action@v1.0.5
      #   with:
      #     # User defined upload name. Visible in Codecov UI
      #     name: Automated Testing Workshop
      #     # Repository upload token - get it from codecov.io
      #     token: 6d0d7df2-5ca2-4687-b1dd-9a837490a1c0
